# Akshara Sundararajan,Ege Tanboga
# 404731846,304735411
# amedrops@g.ucla.edu,ege72282@gmail.com

default:
	echo "Success! lab3b is just a python file"
	cp lab3b.py lab3b
	chmod +x lab3b
clean:
	rm -f lab3b-404731846.tar.gz lab3b

dist:	
	- tar -zvcf lab3b-404731846.tar.gz Makefile README lab3b.py
